// Code generated by gozz:doc github.com/go-zing/gozz. DO NOT EDIT.

package doc

var (
	_types_doc = map[interface{}]map[string]string{
		(*Entity)(nil): _doc_Entity,
		(*User)(nil):   _doc_User,
		(*Book)(nil):   _doc_Book,
	}

	_doc_Entity = map[string]string{
		"":     "abstract type of entity",
		"Id":   "get entity uuid",
		"Name": "get entity name",
	}

	_doc_User = map[string]string{
		"":     "entity for users",
		"Id":   "user uuid",
		"Name": "user name",
	}

	_doc_Book = map[string]string{
		"":     "entity for books",
		"Id":   "book uuid",
		"Name": "book name",
	}
)

func (User) FieldDoc(f string) string { return _doc_User[f] }

func (Book) FieldDoc(f string) string { return _doc_Book[f] }
