// Code generated by gozz:doc github.com/go-zing/gozz. DO NOT EDIT.

package doc

var (
	_types_doc = map[interface{}]map[string]string{
		(*T)(nil): _doc_T,
	}

	_doc_T = map[string]string{
		"":       "1\n2\n\n3\n4\n17",
		"Field":  "6\n\t\t7\n\n8\n9\n10",
		"Field2": "13\n14",
	}
)

func (T) FieldDoc(f string) string { return _doc_T[f] }
