// Code generated by gozz:wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package wire

import (
	wire "github.com/google/wire"
)

// github.com/go-zing/gozz/examples/wire.Application
func Initialize_Application() (*Application, func(), error) {
	panic(wire.Build(_Set))
}
