// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

// Injectors from wire_zinject.go:

// github.com/Just-maple/gozz/examples/wire.Application
func Initialize_Application() (*Application, func(), error) {
	db, err := ProvideSql()
	if err != nil {
		return nil, nil, err
	}
	database := Database{
		DB: db,
	}
	serviceImpl := &ServiceImpl{
		Database: database,
	}
	wire_impl_aop_Service := &_impl_aop_Service{
		_aop_Service: serviceImpl,
	}
	application := &Application{
		Service: wire_impl_aop_Service,
	}
	return application, func() {
	}, nil
}
