// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/Just-maple/gozz/examples/books-all-in-one"
	"github.com/Just-maple/gozz/examples/books-all-in-one/impls"
)

// Injectors from wire_zinject.go:

// github.com/Just-maple/gozz/examples/books-all-in-one.Application
func Initialize_booksallinone_Application() (*books_all_in_one.Application, func(), error) {
	bookServiceImpl := &impls.BookServiceImpl{}
	apis := books_all_in_one.Apis{
		BookService: bookServiceImpl,
	}
	application := &books_all_in_one.Application{
		Apis: apis,
	}
	return application, func() {
	}, nil
}
