// Code generated by gozz:option github.com/go-zing/gozz. DO NOT EDIT.

package option

import ()

type Option func(*Config)

// apply functional options for *Config
func (o *Config) applyOptions(opts ...Option) {
	for _, opt := range opts {
		opt(o)
	}
}

// connect host
func WithHost(v string) Option { return func(o *Config) { o.Host = v } }

// connect port
func WithPort(v string) Option { return func(o *Config) { o.Port = v } }

// database username
func WithUsername(v string) Option { return func(o *Config) { o.Username = v } }

// database password
func WithPassword(v string) Option { return func(o *Config) { o.Password = v } }
