// Code generated by gozz:option github.com/go-zing/gozz. DO NOT EDIT.

package option

import ()

// apply functional options for Config
func (o *Config) applyOptions(opts ...func(*Config)) {
	for _, opt := range opts {
		opt(o)
	}
}

// connect host
func WithHost(v string) func(*Config) { return func(o *Config) { o.Host = v } }

// connect port
func WithPort(v string) func(*Config) { return func(o *Config) { o.Port = v } }

// database username
func WithUsername(v string) func(*Config) { return func(o *Config) { o.Username = v } }

// database password
func WithPassword(v string) func(*Config) { return func(o *Config) { o.Password = v } }

// apply functional options for Config2
func (o *Config2) applyOptions(opts ...func(*Config2)) {
	for _, opt := range opts {
		opt(o)
	}
}

// config url
func WithUrl(v string) func(*Config2) { return func(o *Config2) { o.Url = v } }
